# permissions for end users to edit apppackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-x
    app.kubernetes.io/managed-by: kustomize
  name: apppackage-editor-role
rules:
- apiGroups:
  - go-example.westridgesystems.com
  resources:
  - apppackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-example.westridgesystems.com
  resources:
  - apppackages/status
  verbs:
  - get
