---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - go-example.westridgesystems.com
  resources:
  - apppackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-example.westridgesystems.com
  resources:
  - apppackages/finalizers
  verbs:
  - update
- apiGroups:
  - go-example.westridgesystems.com
  resources:
  - apppackages/status
  verbs:
  - get
  - patch
  - update
